<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Probando Slim Framework</title>
    <link rel="stylesheet" href="<?= PATH ?>/public/css/estilo.css">
</head>
<body>
    <header id="topo-um">
        <div class="container">
            <h1 class="logo-site">Práctica Slim Framework</h1>
            <nav id="menu">
                <ul>
                    <li><a href="<?= PATH ?>" alt="principal">Principal</a></li>
                    <li><a href="<?= PATH ?>/practica" alt="practica">Practica</a></li>
                    <li><a href="<?= PATH ?>/contacto" alt="contacto">Contacto</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <section>
        <div class="container" >